name: AHAHAHA

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
    - name: Download scripts
      run: |
        cd ~
        wget https://raw.githubusercontent.com/GordiNoki/It-s-kinda-funny/main/loop.sh
        wget https://raw.githubusercontent.com/GordiNoki/It-s-kinda-funny/main/preload.sh
    - name: Do stuff
      run: bash ~/preload.sh
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: bash ~/loop.sh
